spring.application.name=OrderManagementSystem

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/orderdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL Initialization
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Timezone
spring.jackson.time-zone=Asia/Kolkata